# Generated by Django 4.1.2 on 2022-10-30 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecart', '0003_order_order_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='tax',
            field=models.IntegerField(default=18),
        ),
    ]
