# Generated by Django 4.1.2 on 2022-10-30 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecart', '0004_cart_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='tax',
            field=models.FloatField(default=18),
        ),
    ]
