# Generated by Django 4.1.2 on 2022-10-30 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecart', '0005_alter_cart_price_alter_cart_tax'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='tax',
        ),
    ]
