# Generated by Django 4.1.2 on 2022-11-01 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecart', '0007_order_order_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tax_price',
            field=models.IntegerField(null=True),
        ),
    ]
