# Generated by Django 4.1.2 on 2022-11-01 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecart', '0009_alter_product_in_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='in_stock',
        ),
        migrations.AddField(
            model_name='product',
            name='in_stocks',
            field=models.BooleanField(default=True),
        ),
    ]
